#!/usr/bin/python

# http://silo.cs.indiana.edu:46271/cgi-bin/02-19-whatever/program
# http://silo.cs.indiana.edu:46271/cgi-bin/02-19-whatever/program?counter=2021&action=Up

import cgi

isaac = cgi.FieldStorage()

import cgitb
cgitb.enable()

print "Content-Type: text/html"     # HTML is following
print                               # blank line, end of headers

print "<TITLE>CGI script output</TITLE>"
print "<H1>This is my first CGI script</H1>"
print "Hello, world!"

print "<hr>", isaac, "<hr>"

if "action" not in isaac or "counter" not in isaac:
  counter = 0
  action = "Unknown"
else:
  action = isaac["action"].value
  counter = isaac["counter"].value

print "action = (", action, ") counter=(", counter, ")"

print """
  <table>
    <tr> <td> <hr>
    <tr> <td> Stage Two: Two Buttons
    <tr> <td>
            <form>
               Welcome, you have clicked the button
               <input type=text name=counter value=%s size=4> times. <p>
               <input type=submit name=action value=Up>
               <input type=submit name=action value=Down>
            </form>
  </table>
""" % (counter)


